bikes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logins/', views.user_logins, name='logins'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.bike_list, name='bike_list'),
    path('booking/', views.booking, name='booking'),
    path('cart/', views.cart, name='cart'),
    path('add-to-cart/<int:bike_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:bike_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('confirm_booking/', views.confirm_booking, name='confirm_booking'),
    path('booking-success/', views.bookings_success, name='booking_success'),
    path('my-bookings/', views.user_bookings, name='user_bookings'),
    path('confirm_payment/<int:booking_id>/', views.confirm_payment, name='confirm_payment'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('authorize-payment/<str:order_id>/', views.authorize_payment, name='authorize_payment'),
    path('profile/', views.user_profile, name='user_profile'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin_manage_bikes/', views.manage_bikes, name='manage_bikes'),
    path('manage_bikes/', views.manage_bikes, name='manage_bikes'),
    path('update_bike/<int:bike_id>/',views.update_bike, name='update_bike'),
    path('delete_bike/<int:bike_id>/',views.delete_bike, name='delete_bike'),
    path('manage_bookings/', views.manage_bookings, name='manage_bookings'),
    path('confirm_booking/<int:booking_id>/', views.confirm_bookings, name='confirm_booking'),
    path('cancel_booking/<int:booking_id>/', views.cancel_bookings, name='cancel_booking'),
    path('return_booking/<int:booking_id>/', views.return_bookings, name='return_booking'),
    path('add_bike/',views.add_bike, name='add_bike'),





]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bikeshare/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bikes.urls')),
]

bikes/models.py
from django.db import models
from django.contrib.auth.models import User

class Bike(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='bikes/', null=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default=0)  # Field for tracking stock

    def __str__(self):
        return self.name

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bike = models.ForeignKey(Bike, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    status_choices = [
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Cancelled', 'Cancelled'),
        ('Returned', 'Returned')
    ]
    status = models.CharField(max_length=20, choices=status_choices, default='Pending')

    def __str__(self):
        return f"{self.user.username} - {self.bike.name}"

    @classmethod
    def get_user_bookings(cls, user):
        return cls.objects.filter(user=user)

    def save(self, *args, **kwargs):
        if self.pk is None:  # New booking
            if self.status == 'Confirmed' and self.bike.stock > 0:
                self.bike.stock -= 1
                self.bike.save()
        else:  # Existing booking
            original = Booking.objects.get(pk=self.pk)
            if original.status == 'Confirmed' and self.status == 'Returned':
                self.bike.stock += 1
                self.bike.save()
        super().save(*args, **kwargs)

    def confirm_return(self):
        if self.status == 'Confirmed':
            self.status = 'Returned'
            self.save()

class Transaction(models.Model):
    booking = models.OneToOneField(Booking, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transaction for Booking: {self.booking.id}"

bikes/forms.py
from django import forms
from .models import Booking, Bike

class BookingForm(forms.ModelForm):
    # Define a hidden field for bike_id
    bike_id = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Booking
        fields = ['bike_id', 'start_date', 'end_date']
class BikeForm(forms.ModelForm):

    class Meta:
        model = Bike
        fields = ['name', 'description', 'image', 'price', 'available', 'stock']

bikes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required

from .models import Bike, Booking, Transaction
from .forms import BookingForm, BikeForm
import requests
from django.urls import reverse
from django.conf import settings
import logging
from django.http import JsonResponse,HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

logger = logging.getLogger(__name__)

def get_access_token():
    token_url = 'https://api-m.sandbox.paypal.com/v1/oauth2/token'
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Authorization': f'Basic {settings.PAYPAL_CLIENT_ID_SECRET_BASE64}'
    }
    data = {
        'grant_type': 'client_credentials'
    }

    response = requests.post(token_url, headers=headers, data=data)

    if response.status_code == 200:
        return response.json()['access_token']
    else:
        raise Exception("Failed to obtain access token")
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Registration successful. You can now log in.')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})
def user_logout(request):
    logout(request)
    return redirect('logins') 
def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('bike_list')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def user_logins(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                # Check if the user is staff (admin)
                if user.is_staff:
                    return redirect('admin_dashboard')
                else:
                    # Redirect non-staff users to another page
                    return redirect('bike_list')  # Or any other page you want to redirect non-admin users
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'logins.html', {'form': form})

@login_required
def add_to_cart(request, bike_id):
    if request.user.is_authenticated:
        bike = Bike.objects.get(id=bike_id)
        cart = request.session.get('cart', {})
        cart[bike_id] = cart.get(bike_id, 0) + 1
        request.session['cart'] = cart
        messages.success(request, 'Item added to cart successfully.')
        return redirect('cart')
    else:
        messages.error(request, 'Please login to add items to cart.')
        return redirect('user_logins')
    
def user_profile(request):
    # Retrieve user's booking history
    bookings = Booking.get_user_bookings(request.user)
    return render(request, 'user_profile.html', {'bookings': bookings})

def bike_list(request):
    bikes = Bike.objects.filter(available=True)
    return render(request, 'bike_list.html', {'bikes': bikes})

def booking(request, bike_id):
    bike = Bike.objects.get(id=bike_id)
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            booking = Booking.objects.create(
                bike=bike,
                start_date=start_date,
                end_date=end_date,
                user=request.user,
                status='Pending'
            )
            bike.available = False
            bike.save()
            return redirect('confirm_booking')
    else:
        form = BookingForm()
    return render(request, 'booking.html', {'form': form, 'bike': bike})

def cart(request):
    cart = request.session.get('cart', {})
    bike_ids = list(cart.keys())
    bikes = Bike.objects.filter(id__in=bike_ids)
    
    total_price = sum(bike.price * cart[str(bike.id)] for bike in bikes)
    
    return render(request, 'cart.html', {'bikes': bikes, 'cart': cart, 'total_price': total_price})

@login_required
def add_to_cart(request, bike_id):
    bike = Bike.objects.get(id=bike_id)
    cart = request.session.get('cart', {})
    cart[bike_id] = cart.get(bike_id, 0) + 1
    request.session['cart'] = cart
    return redirect('cart')

def remove_from_cart(request, bike_id):
    cart = request.session.get('cart', {})
    if str(bike_id) in cart:
        del cart[str(bike_id)]
        request.session['cart'] = cart
    return redirect('cart')

def confirm_booking(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            bike_id = form.cleaned_data['bike_id']
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            
            # Retrieve bike object or return 404 if not found
            bike = get_object_or_404(Bike, id=bike_id)
            
            # Create a new booking with the provided details
            booking = Booking.objects.create(
                bike=bike,
                user=request.user,
                start_date=start_date,
                end_date=end_date,
                status='Pending'
            )
            
            # Remove the booked bike from the cart
            cart = request.session.get('cart', {})
            if str(bike_id) in cart:
                del cart[str(bike_id)]
                request.session['cart'] = cart
            
            # Redirect to payment confirmation page with the booking ID
            return redirect('confirm_payment', booking_id=booking.id)
    else:
        form = BookingForm()

    return render(request, 'confirm_booking.html', {'form': form})

def confirm_payment(request, booking_id):
    # View to handle payment confirmation and redirection to PayPal
    try:
        booking = get_object_or_404(Booking, pk=booking_id)
        bike = booking.bike

        # Calculate total amount based on booking duration and bike price
        if booking.start_date and booking.end_date:
            number_of_days = (booking.end_date - booking.start_date).days   
            total_amount = bike.price * number_of_days
        else:
            total_amount = 0

        # Obtain PayPal access token
        access_token = get_access_token()

        # Set up PayPal API endpoint and headers
        url = 'https://api-m.sandbox.paypal.com/v2/checkout/orders'
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {access_token}'
        }

        # Set up payload for creating a PayPal order
        payload = {
            'intent': 'CAPTURE',
            'purchase_units': [{
                'reference_id': str(booking.id),
                'amount': {
                    'currency_code': 'USD',
                    'value': f'{total_amount:.2f}'
                }
            }],
            'application_context': {
                'return_url': request.build_absolute_uri(reverse('payment_success')),
                'cancel_url': request.build_absolute_uri(reverse('payment_cancel'))
            }
        }

        # Make a POST request to create the PayPal order
        response = requests.post(url, headers=headers, json=payload)

        if response.status_code == 201:
            # If order creation is successful, retrieve the approval URL and redirect
            order_data = response.json()
            approval_url = next(link['href'] for link in order_data['links'] if link['rel'] == 'approve')
            return HttpResponseRedirect(approval_url)
        else:
            # If order creation fails, display an error message and redirect to cart
            messages.error(request, f"Failed to create PayPal order: {response.text}")
            return HttpResponseRedirect(reverse('cart'))

    except Exception as e:
        # Handle any exceptions during the payment confirmation process
        messages.error(request, f"Error connecting to PayPal: {str(e)}")
        return HttpResponseRedirect(reverse('cart'))

def confirm_payment_source(order_id, access_token):
    url = f'https://api-m.sandbox.paypal.com/v2/checkout/orders/{order_id}/confirm-payment-source'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {access_token}'
    }
    payload = {
        "payment_source": {
            "paypal": {
                "name": {
                    "given_name": "John",
                    "surname": "Doe"
                },
                "email_address": "restaurant_customer1@personal.example.com",
                "experience_context": {
                    "payment_method_preference": "IMMEDIATE_PAYMENT_REQUIRED",
                    "brand_name": "EXAMPLE INC",
                    "locale": "en-US",
                    "landing_page": "LOGIN",

bikes/templates/add_bike.html
{% extends 'base_site.html' %}

{% block content %}
<style>
    .add-bike {
    background-color: #f9f9f9;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    margin: 20px auto;
    max-width: 500px;
}

.add-bike h2 {
    margin-bottom: 20px;
    font-size: 24px;
    color: #333;
}

.form-group {
    margin-bottom: 20px;
}

.form-group label {
    display: block;
    margin-bottom: 5px;
    color: #333;
}

.form-group input[type="text"],
.form-group textarea,
.form-group select {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.form-group select {
    padding: 9px; /* Adjust for select height */
}

.btn {
    background-color: #333;
    color: white;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    border-radius: 5px;
    transition: background-color 0.3s ease;
}

.btn:hover {
    background-color: #838181;
}

</style>
<div class="add-bike">
    <h2>Add New Bike</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name:</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="id_description">Description:</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_image">Image:</label>
            {{ form.image }}
        </div>
        <div class="form-group">
            <label for="id_price">Price:</label>
            {{ form.price }}
        </div>
        <div class="form-group">
            <label for="id_available">Available:</label>
            {{ form.available }}
        </div>
        <div class="form-group">
            <label for="id_stock">Stock:</label>
            {{ form.stock }}
        </div>
        <button type="submit" class="btn btn-primary">Add Bike</button>
    </form>
</div>
{% endblock %}

bikes/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bike Rental System</title>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <script src="https://unpkg.com/ionicons@4.2.2/dist/ionicons.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    <style>
        footer{
            padding: 50px;
            height: 40vh;
        }
        ul li a{
            font-size: 2rem;
            margin: 10px;
            text-decoration: none;
        }
        ul li a:hover{
            color: orangered !important;
            border-bottom: 1px solid white;
        }
        .row{
            margin-top: 50px;
        }
    </style>

</head>
<body>
    <header><br><br><br><br>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container justify-content-center">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse container justify-content-center" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bike_list' %}">
                                <img src="{% static 'sikad2.png' %}" alt="" width="60"> Cycle House Iligan
                            </a>
                        </li>
                    </ul>
                   
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'bike_list' %}">
                               Home
                            </a>
                        </li>
                        {% if  user.is_staff %}
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin_dashboard' %}">
                                   Admin dashboard
                                </a>
                            </li>
                            {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cart' %}">
                                Cart
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user_bookings' %}">
                                My Bookings
                            </a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user_profile' %}">
                                Hello, {{ user.username }}
                            </a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">
                                Logout
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logins' %}">
                                Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">
                                Signup
                            </a>
                        </li>
                        {% endif %}
                        <!-- Add more navigation links here -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <main>
        {% block content %}
        <!-- Content of individual pages will be inserted here -->
        {% endblock %}
    </main>
    <br><br><br><br><br>
    
    
    
    
    {% block extra_scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            console.log('JavaScript block executed');
            console.log('Document loaded');  // Debugging: Log document load
            console.log('{{ request.resolver_match.url_name }}');
            console.log('{{ request.session.show_message }}');
    
            // Check if the referrer URL is from the home page
            var referrer = document.referrer;
            console.log('Referrer URL:', referrer);
    
            // If the referrer URL is from the home page and the message should be shown
            if (referrer.includes('{% url "bike_list" %}') && '{{ request.session.show_message }}' === 'True') {
                console.log('Condition matched');  // Debugging: Log condition match
    
                var messageElement = document.getElementById('login-message');
                messageElement.style.display = 'block';
    
                setTimeout(function() {
                    messageElement.style.display = 'none';
                }, 1000);
            }
        });
    </script>
    
    {% endblock %}
    <footer style="text-align: center;" class="bg-dark text-light p-3">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="list-inline quick-links" style="margin-bottom: 0;">
                        <li class="list-inline-item"><a href="#" style="color: white;">Home</a></li>
                        <li class="list-inline-item"><a href="#" style="color: white;">About Us</a></li>
                        <li class="list-inline-item"><a href="#" style="color: white;">Services</a></li>
                        <li class="list-inline-item"><a href="#" style="color: white;">FAQ</a></li>
                        <li class="list-inline-item"><a href="#" style="color: white;">Contact</a></li>
                    </ul>
                    <ul class="list-inline social-icons" style="margin-bottom: 0;">
                        <li class="list-inline-item"><a href="#"><ion-icon name="logo-facebook" style="color: white;"></ion-icon></a></li>
                        <li class="list-inline-item"><a href="#"><ion-icon name="logo-twitter" style="color: white;"></ion-icon></a></li>
                        <li class="list-inline-item"><a href="#"><ion-icon name="logo-instagram" style="color: white;"></ion-icon></a></li>
                        <li class="list-inline-item"><a href="#"><ion-icon name="logo-linkedin" style="color: white;"></ion-icon></a></li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p style="color: white;">&copy; 2024 Bike Rental System</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

bikes/templates/bike_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
  .container h2{
    font-size: 3rem;
    text-align: center;
    margin: 40px;
  }
  .about-us {
    margin: 60px 0;
    padding: 40px;
    background: linear-gradient(rgba(255, 255, 255, 0.8), rgba(255, 255, 255, 0.8)), url("{% static 'about-bg.jpg' %}") center/cover no-repeat;
    border-radius: 10px;
    text-align: center;
  }

  .about-us h2 {
    font-size: 2.5rem;
    margin-bottom: 20px;
    color: #373e44;
    font-family: 'Arial Black', sans-serif;
  }

  .about-us p {
    font-size: 1.2rem;
    line-height: 1.6;
    color: #333;
    max-width: 800px;
    margin: 0 auto;
    font-family: 'Verdana', sans-serif;
  }

  .card {
    border: none;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    transition: transform 0.3s;
  }

  .card:hover {
    transform: translateY(-10px);
  }

  .card-title {
    font-size: 1.5rem;
    color: #0056b3;
    font-family: 'Arial Black', sans-serif;
  }

  .card-text {
    font-size: 1rem;
    color: #555;
    font-family: 'Verdana', sans-serif;
  }.slideshow-container {
    position: relative;
    max-width: 100%;
    margin: auto;
  }

  .mySlides {
    display: none;
  }

  .fade {
    animation: fadeEffect 4.5s;
  }

  @keyframes fadeEffect {
    from {opacity: .4} 
    to {opacity: 1}
  }

  .slideshow-container img {
  border-radius: 10px;
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  width: 100%;
  height: auto;
  max-height: 500px; /* Ensures the image doesn't exceed 500px in height */
  object-fit: cover; /* Ensures the image covers the container proportionally */
}
</style>
<section>
  <img src="{% static 'bikes.jpg' %}" alt="" width="100%" height="730px">
</section>

<div class="container">
  <h2 class="bike_list" style="text-align: center;">𝐑𝐞𝐧𝐭 𝐚 𝐁𝐢𝐤𝐞 𝐧𝐨𝐰</h2>
  <div class="row">
    {% for bike in bikes %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <img src="{{ bike.image.url }}" class="card-img-top" alt="{{ bike.name }}" style="max-height: 200px; object-fit: cover;">
        <div class="card-body">
          <h5 class="card-title">Name: {{ bike.name }}</h5>
          <p class="card-text"><strong>Description: {{ bike.description }}</strong></p>
          <p class="card-text"><strong>Price: ${{ bike.price }}</strong></p>
          <p class="card-text"><strong>Stocks: {{ bike.stock }}</strong></p>
          {% if user.is_authenticated %}
          <form method="post" action="{% url 'add_to_cart' bike.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Add to Cart</button>
          </form>
          {% else %}
          <button type="button" class="btn btn-primary" disabled>Add to Cart</button><br><br>
          <div class="alert alert-danger" role="alert">
            You need to <a href="{% url 'logins' %}">login</a> to add items to the cart.
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col">
      <p>No bikes available.</p>
    </div>
    {% endfor %}
  </div>
</div>
<!-- About Us Section -->
<center>
<div class="container about-us">
  <h2>About Us</h2>
  <div class="slideshow-container">
    <div class="mySlides fade">
      <img src="{% static 'slide1.jpg' %}" alt="Slide 1">
    </div>
    <div class="mySlides fade">
      <img src="{% static 'slide2.jpg' %}" alt="Slide 2">
    </div>
    <div class="mySlides fade">
      <img src="{% static 'slide3.jpg' %}" alt="Slide 3">
    </div>
    <div class="mySlides fade">
      <img src="{% static 'slide4.jpg' %}" alt="Slide 3">
    </div>
    <div class="mySlides fade">
      <img src="{% static 'slide5.jpg' %}" alt="Slide 3">
    </div>
  </div>
  <br>
  <p>Welcome to Cycle House Iligan! We are dedicated to providing the best biking experience in Iligan. Whether you're looking to rent a bike for a day of adventure or need a reliable ride for your daily commute, we have a wide range of bikes to suit your needs. Our team is passionate about cycling and is always here to help you find the perfect bike and accessories. Thank you for choosing Cycle House Iligan. Happy riding!</p>
</div>
</center>
<script>
  var slideIndex = 0;
  showSlides();

  function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}    
    slides[slideIndex-1].style.display = "block";  
    setTimeout(showSlides, 3000); // Change image every 2 seconds
  }
</script>

{% endblock %}

bikes/templates/booking.html
<!-- bikes/booking.html -->

{% extends 'base.html' %}
{% block content %}
  <h2>Booking</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Book Now</button>
  </form>
{% endblock %}

bikes/templates/confirm_booking.html
{% extends 'base.html' %}

{% block content %}
  <h2>Confirm Booking</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Confirm Booking</button>
  </form>
{% endblock %}

bikes/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Bike List</h2>
  <div class="row">
    {% for bike in bikes %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <img src="{{ bike.image.url }}" class="card-img-top" alt="{{ bike.name }}" style="max-height: 200px; object-fit: cover;">
        <div class="card-body">
          <h5 class="card-title">{{ bike.name }}</h5>
          <p class="card-text">{{ bike.description }}</p>
          <p class="card-text"><strong>${{ bike.price }}</strong></p>
          {% if user.is_authenticated %}
          <form method="post" action="{% url 'add_to_cart' bike.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Add to Cart</button>
          </form>
          {% else %}
          <button type="button" class="btn btn-primary" onclick="showLoginMessage()">Add to Cart</button>
          {% endif %}
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col">
      <p>No bikes available.</p>
    </div>
    {% endfor %}
  </div>
</div>

<script>
  function showLoginMessage() {
    $('#login-message').show();
  }
</script>
{% endblock %}

bikes/templates/logins.html
{% extends 'base.html' %}
{% block content %}
<br><br><br>

<div class="container d-flex justify-content-center align-items-center vh-80">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title text-center">Login</h2>
      <form method="post" class="text-center">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

bikes/templates/payment_cancel.html
<!-- payment_cancel.html -->

{% extends 'base.html' %}

{% block content %}
  <h2>Payment Canceled</h2>
  <p>Your payment process has been canceled.</p>
{% endblock %}

bikes/templates/payment_execute.html
<!-- payment_execute.html -->

{% if messages %}
    {% for message in messages %}
        <div>{{ message }}</div>
    {% endfor %}
{% endif %}